# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('snapshot_date', models.DateField(verbose_name='fecha de snapshot')),
                ('bac', models.DecimalField(decimal_places=2, default=0, help_text='Budget at Completion (= project total_value).', max_digits=14, verbose_name='BAC')),
                ('planned_value', models.DecimalField(decimal_places=2, default=0, help_text='Planned Value = SUM(service.total_value * service.expected_progress_pct / 100).', max_digits=14, verbose_name='PV')),
                ('earned_value', models.DecimalField(decimal_places=2, default=0, help_text='Earned Value = SUM(service.total_value * service.progress_pct / 100).', max_digits=14, verbose_name='EV')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, help_text='Actual Cost = SUM(service.real_operative_cost).', max_digits=14, verbose_name='AC')),
                ('spi', models.DecimalField(decimal_places=4, default=0, help_text='Schedule Performance Index = EV / PV.', max_digits=7, verbose_name='SPI')),
                ('cpi', models.DecimalField(decimal_places=4, default=0, help_text='Cost Performance Index = EV / AC.', max_digits=7, verbose_name='CPI')),
                ('schedule_variance', models.DecimalField(decimal_places=2, default=0, help_text='Schedule Variance = EV - PV.', max_digits=14, verbose_name='SV')),
                ('cost_variance', models.DecimalField(decimal_places=2, default=0, help_text='Cost Variance = EV - AC.', max_digits=14, verbose_name='CV')),
                ('eac', models.DecimalField(decimal_places=2, default=0, help_text='Estimate at Completion = BAC / CPI.', max_digits=14, verbose_name='EAC')),
                ('etc', models.DecimalField(decimal_places=2, default=0, help_text='Estimate to Complete = EAC - AC.', max_digits=14, verbose_name='ETC')),
                ('vac', models.DecimalField(decimal_places=2, default=0, help_text='Variance at Completion = BAC - EAC.', max_digits=14, verbose_name='VAC')),
                ('overall_progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avance general (%)')),
                ('expected_progress_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='avance esperado (%)')),
                ('schedule_deviation_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='desviación de cronograma (%)')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ingresos totales')),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costos totales')),
                ('projected_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='margen proyectado (%)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'snapshot de métricas',
                'verbose_name_plural': 'snapshots de métricas',
                'ordering': ['-snapshot_date'],
                'indexes': [models.Index(fields=['project', 'snapshot_date'], name='idx_metric_proj_date')],
                'unique_together': {('project', 'snapshot_date')},
            },
        ),
    ]
