# Generated by Django 5.1.15 on 2026-03-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmetricsnapshot',
            name='planned_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Planned Cost = SUM(service.estimated_operative_cost * service.expected_progress_pct / 100).', max_digits=14, verbose_name='PC'),
        ),
    ]
