# Generated by Django 5.1.15 on 2026-03-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('terceros', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='terceros.thirdparty', verbose_name='tercero'),
        ),
    ]
