# Generated by Django 5.2.12 on 2026-04-01 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_colombia_data'),
        ('projects', '0002_project_third_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='geography.municipality', verbose_name='municipio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='ciudad / municipio (texto libre)'),
        ),
    ]
