# Generated by Django 5.2.12 on 2026-04-01 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_add_municipality_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='valor')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En ejecución'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=20, verbose_name='estado')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'alcance contractual',
                'verbose_name_plural': 'alcances contractuales',
                'ordering': ['created_at'],
            },
        ),
    ]
