# Generated by Django 5.2.12 on 2026-04-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_document_to_prerequisite'),
        ('projects', '0004_add_project_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprerequisite',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prerequisites', to='documents.projectdocument', verbose_name='documento adjunto'),
        ),
    ]
