# Generated by Django 5.1.15 on 2026-04-01 15:37

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_document_to_prerequisite'),
        ('services', '0003_servicetemplate_operative_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrerequisiteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('PREREQUISITO', 'Prerequisito'), ('GESTION_RIESGO', 'Gestión de Riesgo'), ('COMUNICACION', 'Comunicación')], max_length=30, verbose_name='categoría de prerequisito')),
                ('prerequisite_type', models.CharField(help_text='Ej. "Técnicos", "Ficha de Proyecto", "Canal de Slack".', max_length=100, verbose_name='tipo de prerequisito')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('weight_pct', models.DecimalField(decimal_places=2, default=Decimal('8.33'), max_digits=5, verbose_name='peso (%)')),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_templates', to='services.projectcategory', verbose_name='categoría de proyecto')),
            ],
            options={
                'verbose_name': 'plantilla de prerequisito',
                'verbose_name_plural': 'plantillas de prerequisitos',
                'ordering': ['project_category', 'category', 'prerequisite_type'],
            },
        ),
    ]
