# Generated by Django 5.1.15 on 2026-04-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_add_prerequisite_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='prerequisitetemplate',
            name='notes',
            field=models.TextField(blank=True, verbose_name='descripción / notas'),
        ),
        migrations.AddField(
            model_name='prerequisitetemplate',
            name='reference_file',
            field=models.FileField(blank=True, null=True, upload_to='prereq_templates/', verbose_name='archivo adjunto'),
        ),
        migrations.AddField(
            model_name='prerequisitetemplate',
            name='reference_link',
            field=models.URLField(blank=True, help_text='URL a un documento o recurso de referencia.', verbose_name='enlace de referencia'),
        ),
    ]
