# Generated by Django 5.1.15 on 2026-04-01 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_access_package'),
        ('projects', '0007_add_notes_link_file_to_prereq_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='access_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='accounts.accesspackage', verbose_name='paquete de acceso'),
        ),
        migrations.AlterField(
            model_name='project',
            name='access_type',
            field=models.CharField(choices=[('PREMIUM', 'PREMIUM ACCESS'), ('STANDARD', 'STANDARD ACCESS')], default='STANDARD', max_length=20, verbose_name='tipo de acceso (legado)'),
        ),
    ]
