# Generated by Django 5.1.15 on 2026-04-06 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_data_migrate_access_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceinstance',
            name='phase_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_instances', to='projects.projectphaseinstance', verbose_name='instancia de fase'),
        ),
    ]
