# Generated by Django 5.1.15 on 2026-04-11 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_work_schedule'),
        ('projects', '0010_phase_instance_nullable'),
        ('services', '0015_deliverable_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceInstanceAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='orden')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='horas estimadas')),
                ('assigned_professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_assignments', to=settings.AUTH_USER_MODEL, verbose_name='profesional asignado')),
                ('responsible_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='rol responsable')),
                ('service_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instance_assignments', to='services.serviceactivity', verbose_name='acción de servicio')),
                ('service_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_assignments', to='projects.serviceinstance', verbose_name='instancia de servicio')),
            ],
            options={
                'verbose_name': 'asignación de acción',
                'verbose_name_plural': 'asignaciones de acciones',
                'ordering': ['service_instance', 'order'],
            },
        ),
    ]
