# Generated by Django 5.1.15 on 2026-04-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_serviceinstanceaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstanceaction',
            name='actual_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='horas reales'),
        ),
        migrations.AddField(
            model_name='serviceinstanceaction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de completado'),
        ),
        migrations.AddField(
            model_name='serviceinstanceaction',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='completada'),
        ),
    ]
