# Generated by Django 5.1.15 on 2026-04-11 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_action_progress_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='qué se hizo')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='progress_logs/attachments/', verbose_name='adjunto')),
                ('folder_link', models.URLField(blank=True, max_length=500, null=True, verbose_name='link de carpeta')),
                ('start_datetime', models.DateTimeField(verbose_name='hora inicio real')),
                ('end_datetime', models.DateTimeField(verbose_name='hora fin real')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='projects.serviceinstanceaction', verbose_name='acción')),
                ('executed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_logs', to=settings.AUTH_USER_MODEL, verbose_name='ejecutado por')),
            ],
            options={
                'verbose_name': 'registro de avance',
                'verbose_name_plural': 'registros de avance',
                'ordering': ['-created_at'],
            },
        ),
    ]
