# Generated by Django 5.1.15 on 2026-04-11 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_add_action_progress_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='approval_notes',
            field=models.TextField(blank=True, verbose_name='observaciones de aprobación'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='approval_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=10, verbose_name='estado de aprobación'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_services', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por'),
        ),
    ]
