# Generated by Django 5.1.15 on 2026-04-24 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_costcentersubcategory'),
        ('projects', '0014_add_service_approval_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='financials.costcentermapping', verbose_name='centro de costo'),
        ),
    ]
