# Generated by Django 5.1.15 on 2026-05-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_project_cost_center_fk'),
        ('terceros', '0002_migrate_clients_to_thirdparty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
