# Generated by Django 5.2.12 on 2026-05-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_remove_project_client_delete_client'),
        ('terceros', '0003_thirdparty_document_type_alter_thirdparty_nit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionprogresslog',
            name='description',
            field=models.TextField(blank=True, verbose_name='qué se hizo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='terceros.thirdparty', verbose_name='cliente'),
        ),
    ]
