# Generated by Django 6.0.5 on 2026-05-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_actionprogresslog_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Foto representativa del proyecto (fachada, render, etc.).', null=True, upload_to='projects/covers/', verbose_name='imagen de portada'),
        ),
    ]
