# Generated by Django 5.1.15 on 2026-03-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('LA', 'Líder de Área'), ('INT', 'Interventor'), ('VS', 'Visor de Seguimiento'), ('VL', 'Visor Libre'), ('DM', 'Director de Medios'), ('AI_I', 'AI Individual'), ('AI_M', 'AI Masivo'), ('DO', 'Dirección Operativa'), ('LP', 'Líder de Proyecto')], max_length=10, unique=True, verbose_name='código'),
        ),
    ]
