# Generated by Django 5.1.15 on 2026-04-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_role_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['code'], 'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AddField(
            model_name='role',
            name='can_access_all_projects',
            field=models.BooleanField(default=False, help_text='Si está activo, ve todos los proyectos. Si no, solo los asignados.', verbose_name='ve todos los proyectos'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_access_financials',
            field=models.BooleanField(default=False, help_text='Puede ver valores, tarifas y rentabilidad.', verbose_name='acceso a datos financieros'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='role',
            name='is_leader',
            field=models.BooleanField(default=False, help_text='Aparece en el selector de líder al crear/editar proyectos.', verbose_name='puede liderar proyectos'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(help_text='Ej. "LP", "LA", "DO".', max_length=20, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, help_text='Describe qué puede hacer este rol en la plataforma.', verbose_name='descripción / permisos'),
        ),
    ]
