# Generated by Django 5.1.15 on 2026-04-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_expand_role_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej. "ESSENTIAL", "PREMIUM".', max_length=30, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción / qué incluye')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'paquete de acceso',
                'verbose_name_plural': 'paquetes de acceso',
                'ordering': ['code'],
            },
        ),
    ]
