# Generated by Django 5.1.15 on 2026-04-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_access_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej. "Tiempo completo", "Medio tiempo".', max_length=100, verbose_name='nombre')),
                ('weekly_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='horas por semana')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'jornada laboral',
                'verbose_name_plural': 'jornadas laborales',
                'ordering': ['-weekly_hours'],
            },
        ),
    ]
