# Generated by Django 6.0.5 on 2026-05-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_work_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_create_projects',
            field=models.BooleanField(default=False, help_text='Puede crear nuevos proyectos en el sistema.', verbose_name='puede crear proyectos'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_edit_projects',
            field=models.BooleanField(default=False, help_text='Puede editar y eliminar proyectos existentes.', verbose_name='puede editar proyectos'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_allocations',
            field=models.BooleanField(default=False, help_text='Puede asignar y modificar la distribución de capacidad del equipo.', verbose_name='puede gestionar capacidad'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_manage_third_parties',
            field=models.BooleanField(default=False, help_text='Puede crear y editar clientes, proveedores y terceros.', verbose_name='puede gestionar terceros'),
        ),
    ]
