# Generated by Django 6.0.5 on 2026-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_role_permission_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_import_data',
            field=models.BooleanField(default=False, help_text='Puede usar el asistente de importación masiva de datos.', verbose_name='puede importar datos'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_calendar',
            field=models.BooleanField(default=False, help_text='Puede acceder a la sincronización y vista de calendario.', verbose_name='ve sección Calendario'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_capacity',
            field=models.BooleanField(default=False, help_text='Puede acceder a los módulos de capacidad y heatmap del equipo.', verbose_name='ve sección Capacidad / Heatmap'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_organization',
            field=models.BooleanField(default=False, help_text='Puede acceder a la configuración organizacional.', verbose_name='ve sección Organización'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_portfolio',
            field=models.BooleanField(default=False, help_text='Puede acceder a la vista general de proyectos (Portfolio).', verbose_name='ve sección Portfolio'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_pricing',
            field=models.BooleanField(default=False, help_text='Puede acceder al dashboard de tarifas y precios.', verbose_name='ve sección Pricing'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_services',
            field=models.BooleanField(default=False, help_text='Puede acceder al catálogo de servicios.', verbose_name='ve sección Servicios'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_terceros',
            field=models.BooleanField(default=False, help_text='Puede acceder al módulo de clientes y terceros.', verbose_name='ve sección Terceros'),
        ),
        migrations.AddField(
            model_name='role',
            name='can_view_timetracking',
            field=models.BooleanField(default=False, help_text='Puede acceder al registro y reporte de tiempo.', verbose_name='ve sección Mi Tiempo'),
        ),
    ]
