from django.urls import path

from apps.services import views, views_pricing

app_name = "services"

urlpatterns = [
    path(
        "categories/",
        views.ProjectCategoryListView.as_view(),
        name="category_list",
    ),
    path(
        "categories/crear/",
        views.ProjectCategoryCreateView.as_view(),
        name="category_create",
    ),
    path(
        "categories/<int:pk>/editar/",
        views.ProjectCategoryUpdateView.as_view(),
        name="category_update",
    ),
    path(
        "categories/<int:pk>/eliminar/",
        views.ProjectCategoryDeleteView.as_view(),
        name="category_delete",
    ),
    path(
        "subcategories/",
        views.ServiceSubCategoryListView.as_view(),
        name="subcategory_list",
    ),
    path(
        "subcategories/crear/",
        views.ServiceSubCategoryCreateView.as_view(),
        name="subcategory_create",
    ),
    path(
        "subcategories/<int:pk>/editar/",
        views.ServiceSubCategoryUpdateView.as_view(),
        name="subcategory_update",
    ),
    path(
        "subcategories/<int:pk>/eliminar/",
        views.ServiceSubCategoryDeleteView.as_view(),
        name="subcategory_delete",
    ),
    path(
        "phases/",
        views.ProjectPhaseListView.as_view(),
        name="phase_list",
    ),
    path(
        "phases/crear/",
        views.ProjectPhaseCreateView.as_view(),
        name="phase_create",
    ),
    path(
        "phases/<int:pk>/editar/",
        views.ProjectPhaseUpdateView.as_view(),
        name="phase_update",
    ),
    path(
        "phases/<int:pk>/eliminar/",
        views.ProjectPhaseDeleteView.as_view(),
        name="phase_delete",
    ),
    path(
        "templates/",
        views.ServiceTemplateListView.as_view(),
        name="servicetemplate_list",
    ),
    path(
        "templates/<int:pk>/",
        views.ServiceTemplateDetailView.as_view(),
        name="servicetemplate_detail",
    ),
    path(
        "templates/create/",
        views.ServiceTemplateCreateView.as_view(),
        name="servicetemplate_create",
    ),
    path(
        "templates/<int:pk>/update/",
        views.ServiceTemplateUpdateView.as_view(),
        name="servicetemplate_update",
    ),
    path(
        "templates/<int:pk>/delete/",
        views.ServiceTemplateDeleteView.as_view(),
        name="servicetemplate_delete",
    ),
    # Pricing dashboard
    path(
        "pricing/",
        views.PricingDashboardView.as_view(),
        name="pricing_dashboard",
    ),
    path(
        "pricing/<int:pk>/editar/",
        views.ServiceTemplateInlineEditView.as_view(),
        name="pricing_inline_edit",
    ),
    path(
        "pricing/<int:pk>/cancelar/",
        views.ServiceTemplateInlineCancelView.as_view(),
        name="pricing_inline_cancel",
    ),
    # Pricing change requests
    path(
        "pricing-requests/",
        views_pricing.PricingChangeRequestListView.as_view(),
        name="pricing_request_list",
    ),
    path(
        "pricing-requests/<int:si_pk>/crear/",
        views_pricing.PricingChangeRequestCreateView.as_view(),
        name="pricing_request_create",
    ),
    path(
        "pricing-requests/<int:pk>/revisar/",
        views_pricing.PricingChangeRequestReviewView.as_view(),
        name="pricing_request_review",
    ),
]
