# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Ej. 'D3', 'E1', 'P1'.", max_length=10, unique=True, verbose_name='código')),
                ('name', models.CharField(help_text="Ej. 'Vivienda Campestre', 'Edificios en Altura'.", max_length=200, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'categoría de proyecto',
                'verbose_name_plural': 'categorías de proyecto',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='número')),
                ('name', models.CharField(help_text="Ej. 'Fase 1', 'Fase 2', 'Fase 3'.", max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'fase de proyecto',
                'verbose_name_plural': 'fases de proyecto',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Ej. 'D0.1', 'V1.2'.", max_length=20, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('base_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='precio unitario base')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='horas estimadas')),
                ('estimated_days', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='días estimados')),
                ('target_margin_pct', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='margen objetivo (%)')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_templates', to='services.projectcategory', verbose_name='categoría')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_templates', to='services.projectphase', verbose_name='fase')),
            ],
            options={
                'verbose_name': 'plantilla de servicio',
                'verbose_name_plural': 'plantillas de servicio',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ServiceActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=1, verbose_name='orden')),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='horas estimadas')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('responsible_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_activities', to='accounts.role', verbose_name='rol responsable')),
                ('service_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='services.servicetemplate', verbose_name='plantilla de servicio')),
            ],
            options={
                'verbose_name': 'actividad de servicio',
                'verbose_name_plural': 'actividades de servicio',
                'ordering': ['service_template', 'order'],
            },
        ),
    ]
