# Generated by Django 5.1.15 on 2026-03-08 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_third_party'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('PENDING', 'En Revisión'), ('APPROVED', 'Aprobado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=20, verbose_name='estado')),
                ('current_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='precio unitario actual')),
                ('current_projected_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='horas proyectadas actuales')),
                ('proposed_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='precio unitario propuesto')),
                ('proposed_projected_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='horas proyectadas propuestas')),
                ('justification', models.TextField(verbose_name='justificación')),
                ('review_notes', models.TextField(blank=True, verbose_name='notas de revisión')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de revisión')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='solicitado por')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='revisado por')),
                ('service_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_requests', to='projects.serviceinstance', verbose_name='instancia de servicio')),
            ],
            options={
                'verbose_name': 'solicitud de cambio de precio',
                'verbose_name_plural': 'solicitudes de cambio de precio',
                'ordering': ['-created_at'],
            },
        ),
    ]
