# Generated by Django 5.2.12 on 2026-03-20 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('services', '0002_pricingchangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='operative_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_templates', to='organizations.operativeline', verbose_name='línea operativa'),
        ),
    ]
