# Generated by Django 5.1.15 on 2026-04-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicetemplate_operative_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Ej. '01', '02', '03'.", max_length=5, unique=True, verbose_name='código')),
                ('name', models.CharField(help_text="Ej. 'Urbanismo', 'Edificación', 'Complementario'.", max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'sub categoría de servicio',
                'verbose_name_plural': 'sub categorías de servicio',
                'ordering': ['code'],
            },
        ),
    ]
