# Generated by Django 5.1.15 on 2026-04-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_service_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text="Ej. 'Workstation Alta Gama'. Puede dejarse en blanco.", max_length=200, verbose_name='nombre')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor del equipo ($COP)')),
                ('depreciation_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='depreciación por hora ($COP)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'hardware',
                'verbose_name_plural': 'hardware',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('annual_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor anual ($COP)')),
                ('hourly_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor por hora ($COP)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'software',
                'verbose_name_plural': 'software',
                'ordering': ['name'],
            },
        ),
    ]
