# Generated by Django 5.1.15 on 2026-04-06 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicetemplate_phase_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_templates', to='services.servicesubcategory', verbose_name='sub categoría'),
        ),
    ]
