# Generated by Django 5.1.15 on 2026-04-06 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_work_schedule'),
        ('services', '0007_add_subcategory_to_servicetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='responsible_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_templates', to='accounts.role', verbose_name='rol responsable'),
        ),
    ]
