# Generated by Django 5.1.15 on 2026-04-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_add_responsible_role_to_servicetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='consumables_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='consumibles/hora ($COP)'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='contingency_pct',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='desfase (%)'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='hardware_cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='hardware depreciación/hora ($COP)'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='honorarios/hora ($COP)'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='negotiation_pct',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='margen negociación (%)'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='software_cost_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='software licencias/hora ($COP)'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='subcontracts',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='subcontratos ($COP)'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='utility_pct',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='utilidad (%)'),
        ),
    ]
