# Generated by Django 5.2.12 on 2026-04-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_add_pricing_inputs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceactivity',
            options={'ordering': ['service_template', 'order']},
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=400, verbose_name='nombre del entregable')),
                ('unit', models.CharField(blank=True, help_text='Ej. Proyecto, 100m2, Und, 15 ha.', max_length=100, verbose_name='unidad')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='orden')),
                ('service_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='services.servicetemplate', verbose_name='servicio')),
            ],
            options={
                'verbose_name': 'entregable',
                'verbose_name_plural': 'entregables',
                'ordering': ['service_template', 'order', 'name'],
            },
        ),
    ]
