# Generated by Django 5.2.12 on 2026-04-11 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_deliverable'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='orden')),
                ('deliverable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_activities', to='services.deliverable', verbose_name='entregable')),
            ],
            options={
                'verbose_name': 'actividad clave',
                'verbose_name_plural': 'actividades clave',
                'ordering': ['deliverable', 'order', 'name'],
            },
        ),
    ]
