# Generated by Django 5.2.12 on 2026-04-11 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_keyactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceactivity',
            name='key_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='services.keyactivity', verbose_name='actividad clave'),
        ),
    ]
