# Generated by Django 5.2.12 on 2026-04-11 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('services', '0012_serviceactivity_key_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesubcategory',
            name='operative_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='organizations.operativeline', verbose_name='línea operativa'),
        ),
    ]
