# Generated by Django 5.2.12 on 2026-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_projectcategory_operative_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='cantidad'),
        ),
    ]
