# Generated by Django 5.1.15 on 2026-04-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_deliverable_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de adquisición'),
        ),
        migrations.AddField(
            model_name='software',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento'),
        ),
    ]
