# Generated by Django 5.1.15 on 2026-04-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_software_acquisition_expiration_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='auto_renewal',
            field=models.BooleanField(default=False, verbose_name='renovación automática'),
        ),
        migrations.AddField(
            model_name='software',
            name='license_type',
            field=models.CharField(choices=[('perpetua', 'Perpetua'), ('suscripcion', 'Suscripción'), ('por_usuario', 'Por usuario')], default='suscripcion', max_length=20, verbose_name='tipo de licencia'),
        ),
        migrations.AddField(
            model_name='software',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notas'),
        ),
        migrations.AddField(
            model_name='software',
            name='seats',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='cantidad de puestos'),
        ),
        migrations.AddField(
            model_name='software',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, verbose_name='proveedor'),
        ),
        migrations.AddField(
            model_name='software',
            name='vendor_url',
            field=models.URLField(blank=True, verbose_name='URL del proveedor'),
        ),
        migrations.AddField(
            model_name='software',
            name='version',
            field=models.CharField(blank=True, max_length=100, verbose_name='versión'),
        ),
    ]
