# Generated by Django 5.1.15 on 2026-04-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_software_vendor_version_type_seats_renewal_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='monthly_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor mensual ($COP)'),
        ),
    ]
