# Generated by Django 5.1.15 on 2026-04-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_software_monthly_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwarePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_date', models.DateField(verbose_name='fecha de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='valor pagado ($COP)')),
                ('notes', models.CharField(blank=True, max_length=300, verbose_name='notas')),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='services.software', verbose_name='software')),
            ],
            options={
                'verbose_name': 'pago de software',
                'verbose_name_plural': 'pagos de software',
                'ordering': ['-payment_date'],
            },
        ),
    ]
