# Generated by Django 5.1.15 on 2026-04-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_softwarepayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='software',
            name='is_direct_cost',
            field=models.BooleanField(default=True, verbose_name='costo directo'),
        ),
    ]
