# Generated by Django 5.1.15 on 2026-04-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_software_is_direct_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardware',
            name='brand',
            field=models.CharField(blank=True, max_length=100, verbose_name='marca'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='depreciation_years',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='años de depreciación'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='is_direct_cost',
            field=models.BooleanField(default=True, verbose_name='costo directo'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='ubicación'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='modelo'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de compra'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='número de serie'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='warranty_expiration',
            field=models.DateField(blank=True, null=True, verbose_name='garantía hasta'),
        ),
        migrations.CreateModel(
            name='HardwareMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_type', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('garantia', 'Garantía')], default='preventivo', max_length=20, verbose_name='tipo')),
                ('date', models.DateField(verbose_name='fecha')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costo ($COP)')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='proveedor / técnico')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='próximo mantenimiento')),
                ('hardware', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='services.hardware', verbose_name='equipo')),
            ],
            options={
                'verbose_name': 'mantenimiento',
                'verbose_name_plural': 'mantenimientos',
                'ordering': ['-date'],
            },
        ),
    ]
