# Generated by Django 5.2.12 on 2026-05-08 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_hardware_expand_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='hardwares',
            field=models.ManyToManyField(blank=True, help_text='Hardware que aplica a este servicio. La depreciación/hora se autocalcula de la suma.', related_name='service_templates_using', to='services.hardware', verbose_name='hardware aplicable'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='softwares',
            field=models.ManyToManyField(blank=True, help_text='Software que aplica a este servicio. El costo/hora se autocalcula de la suma.', related_name='service_templates_using', to='services.software', verbose_name='software aplicable'),
        ),
    ]
