# Generated by Django 5.2.14 on 2026-05-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_servicetemplate_hardwares_servicetemplate_softwares'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='name',
            field=models.TextField(verbose_name='nombre del entregable'),
        ),
        migrations.AlterField(
            model_name='keyactivity',
            name='name',
            field=models.TextField(verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='serviceactivity',
            name='name',
            field=models.TextField(verbose_name='nombre'),
        ),
    ]
