# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, verbose_name='codigo')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('time_invested_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='horas invertidas')),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En progreso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20, verbose_name='estado')),
                ('external_discipline', models.CharField(blank=True, max_length=200, verbose_name='disciplina externa')),
                ('response', models.TextField(blank=True, verbose_name='respuesta')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis', to=settings.AUTH_USER_MODEL, verbose_name='profesional')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfis', to='projects.project', verbose_name='proyecto')),
                ('service_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfis', to='projects.serviceinstance', verbose_name='instancia de servicio')),
            ],
            options={
                'verbose_name': 'RFI',
                'verbose_name_plural': 'RFIs',
                'ordering': ['-created_at'],
            },
        ),
    ]
