# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekly_available_hours', models.DecimalField(decimal_places=2, default=40, max_digits=6, verbose_name='horas disponibles por semana')),
                ('effective_from', models.DateField(verbose_name='vigente desde')),
                ('effective_until', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacities', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'capacidad de miembro',
                'verbose_name_plural': 'capacidades de miembros',
                'ordering': ['user', 'effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha de fin')),
                ('weekly_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='horas semanales')),
                ('allocation_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='porcentaje de asignación')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='projects.project', verbose_name='proyecto')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role', verbose_name='rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'asignación de proyecto',
                'verbose_name_plural': 'asignaciones de proyecto',
                'ordering': ['user', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='CapacityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('OVERLOAD', 'Sobrecarga'), ('UNDERLOAD', 'Subcarga'), ('CONFLICT', 'Conflicto')], max_length=20, verbose_name='tipo de alerta')),
                ('week_start', models.DateField(verbose_name='inicio de semana')),
                ('allocated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='horas asignadas')),
                ('available_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='horas disponibles')),
                ('details', models.TextField(blank=True, verbose_name='detalles')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resuelta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_alerts', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'alerta de capacidad',
                'verbose_name_plural': 'alertas de capacidad',
                'ordering': ['-week_start'],
            },
        ),
    ]
