# Generated by Django 5.2.12 on 2026-03-08 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capacity', '0001_initial'),
        ('projects', '0002_project_third_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectallocation',
            name='service_instance',
            field=models.ForeignKey(blank=True, help_text='Opcional: vincular esta asignación a un servicio específico.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_allocations', to='projects.serviceinstance', verbose_name='instancia de servicio'),
        ),
    ]
