"""
Management command: seed_key_activities
Carga las actividades clave desde la hoja D.sign DATA del archivo
05. Services_05.25.xlsm en el modelo KeyActivity.

Idempotente: usa get_or_create. Se puede ejecutar múltiples veces.

Uso:
    python manage.py seed_key_activities
"""

from django.core.management.base import BaseCommand

DATA = [
('D0.1', 'Canales de comunicación y almacenamiento', 'Gestión documental y creación de canales', 1),
('D0.1', 'Diagnóstico Inicial del proyecto', 'Recolección de insumos preliminares', 1),
('D0.1', 'Diagnóstico Inicial del proyecto', 'Visita inicial al lote o análisis de modelo preexistente', 2),
('D0.1', 'Encuesta formato google forms', 'Recolección de insumos preliminares', 1),
('D0.1', 'Programación', 'Gestión documental y creación de canales', 1),
('D0.2', 'Construcción de Concepto', 'Conceptualización / Referentes', 1),
('D0.2', 'Diagnóstico Inicial del proyecto', 'Taller de diseño', 1),
('D0.2', 'Diagnóstico Inicial del proyecto', 'Preliminares', 2),
('D0.2', 'Estudio contextual', 'Análisis Normativo', 1),
('D0.2', 'Estudio contextual', 'Análisis Bioclimático', 2),
('D0.2', 'Estudio contextual', 'Resultado del análisis bioclimático', 3),
('D0.3', 'Entrega', 'Planeación de experiencia de entrega', 1),
('D0.3', 'Presentación de desarrollo arquitectónico', 'Antecedentes', 1),
('D0.3', 'Presentación de desarrollo arquitectónico', 'Conceptualización', 2),
('D0.3', 'Presentación de desarrollo arquitectónico', 'Renders e Imágenes', 3),
('D1.1', 'Modelo Tridimensional, Viewer 360 Escala Urbana', 'Creación de topografía', 1),
('D1.1', 'Modelo Tridimensional, Viewer 360 Escala Urbana', 'Planteamiento Vial', 2),
('D1.1', 'Modelo Tridimensional, Viewer 360 Escala Urbana', 'Lotificación', 3),
('D1.10', 'Planimetría Arquitectónica del Urbanismo', 'Planta de urbanismo general', 1),
('D1.10', 'Planimetría Arquitectónica del Urbanismo', 'Planta de etapas de desarrollo', 2),
('D1.10', 'Planimetría Arquitectónica del Urbanismo', 'Secciones generales', 3),
('D1.10', 'Planimetría Arquitectónica del Urbanismo', 'Tabla de movimientos de tierra', 4),
('D1.11', 'Planimetría Arquitectónica Elementos Complementarios', 'Planta de Localización Elemento Complementario', 1),
('D1.11', 'Planimetría Arquitectónica Elementos Complementarios', 'Planta Arquitectónica Elemento Complementario', 2),
('D1.11', 'Planimetría Arquitectónica Elementos Complementarios', 'Planta de cubierta Elemento Complementario', 3),
('D1.11', 'Planimetría Arquitectónica Elementos Complementarios', 'Secciones generales Elemento Complementario', 4),
('D1.11', 'Planimetría Arquitectónica Elementos Complementarios', 'Fachadas Elemento Complementario', 5),
('D1.11', 'Planimetría Arquitectónica Elementos Complementarios', 'Isométricos (Elemento complementario)', 6),
('D1.11', 'Planimetría Arquitectónica Elementos Complementarios', 'Cuadro de áreas (Elemento complementario)', 7),
('D1.12', 'Planimetría Arquitectónica Edificación', 'Planta de Localización Edificación', 1),
('D1.12', 'Planimetría Arquitectónica Edificación', 'Planta Arquitectónica Edificación', 2),
('D1.12', 'Planimetría Arquitectónica Edificación', 'Planta de cubierta Edificación', 3),
('D1.12', 'Planimetría Arquitectónica Edificación', 'Secciones generales Edificación', 4),
('D1.12', 'Planimetría Arquitectónica Edificación', 'Fachadas Edificación', 5),
('D1.12', 'Planimetría Arquitectónica Edificación', 'Isométricos (Edificación)', 6),
('D1.12', 'Planimetría Arquitectónica Edificación', 'Cuadro de áreas (Edificación)', 7),
('D1.13', 'Especificaciones del Urbanismo', 'Montaje de formato de especificaciones', 1),
('D1.13', 'Especificaciones del Urbanismo', 'Relacionar formato con la planimetría generada', 2),
('D1.14', 'Especificaciones de Elemento Complementario', 'Especificación general de los materiales a implementar', 1),
('D1.14', 'Especificaciones de Elemento Complementario', 'Montaje de formato de especificaciones', 2),
('D1.14', 'Especificaciones de Elemento Complementario', 'Asignar materiales en 3D', 3),
('D1.14', 'Especificaciones de Elemento Complementario', 'Asignar materiales en planimetría', 4),
('D1.14', 'Especificaciones de Elemento Complementario', 'Presentar información', 5),
('D1.15', 'Especificaciones', 'Especificación general de los materiales a implementar', 1),
('D1.15', 'Especificaciones', 'Montaje de formato de especificaciones', 2),
('D1.16', 'Modelo Tridimensional  a través de LINK en nube.', 'Preparativos del modelo', 1),
('D1.16', 'Modelo Tridimensional  a través de LINK en nube.', 'Detallar el modelo', 2),
('D1.16', 'Modelo Tridimensional  a través de LINK en nube.', 'Coordinación interdisciplinaria', 3),
('D1.17', 'Modelo Tridimensional  a través de LINK en nube.', 'Preparativos del modelo', 1),
('D1.17', 'Modelo Tridimensional  a través de LINK en nube.', 'Detallar el modelo', 2),
('D1.18', 'Planimetría Arquitectónica de Detalle (Acabados en muros)', 'Detalle de mobiliario urbano', 1),
('D1.18', 'Planimetría Arquitectónica de Detalle (Borde de losa)', 'Detalle de cotas de implantación y fichas de lotes', 1),
('D1.18', 'Planimetría Arquitectónica de Detalle (Cielos)', 'Detalle de iluminación', 1),
('D1.18', 'Planimetría Arquitectónica de Detalle (Cubiertas y pérgolas)', 'Detalle de sección de senderos y superficies (pisos)', 1),
('D1.18', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de iluminación', 1),
('D1.18', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de totéms y portones', 2),
('D1.18', 'Planimetría Arquitectónica de Detalle (Pisos)', 'Detalle de sección vial', 1),
('D1.18', 'Planimetría Arquitectónica de Detalle (Puertas y Ventanas)', 'Detalle de coordinación con otras disciplinas', 1),
('D1.19', 'Planimetría Arquitectónica de Detalle (Acabados en muros)', 'Detalle de Tipos de acabados en muros', 1),
('D1.19', 'Planimetría Arquitectónica de Detalle (Borde de losa)', 'Detalle de borde de losa', 1),
('D1.19', 'Planimetría Arquitectónica de Detalle (Carpintería)', 'Detalle de Funcionamiento y composición de carpintería', 1),
('D1.19', 'Planimetría Arquitectónica de Detalle (Cielos)', 'Detalle de iluminación', 1),
('D1.19', 'Planimetría Arquitectónica de Detalle (Cubiertas y pérgolas)', 'Detalle de elementos especiales', 1),
('D1.19', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de iluminación', 1),
('D1.19', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de modulación y tipos de cielo', 2),
('D1.19', 'Planimetría Arquitectónica de Detalle (Pisos)', 'Detalle de modulación y tipos de piso', 1),
('D1.19', 'Planimetría Arquitectónica de Detalle (Puertas y Ventanas)', 'Detalle de Funcionamiento y composición de puertas y ventanas', 1),
('D1.2', 'Modelado Tridimensional Viewer 360, zona complementaria', 'Diseño y modelado de zona complementaria (planta)', 1),
('D1.2', 'Modelado Tridimensional Viewer 360, zona complementaria', 'Diseño y modelado de zona complementaria (fachada)', 2),
('D1.2', 'Modelado Tridimensional Viewer 360, zona complementaria', 'Integración a Topografía zona complementaria', 3),
('D1.2', 'Modelado Tridimensional Viewer 360, zona complementaria', 'Exportar Modelo zona complementaria', 4),
('D1.20', 'Especificaciones de proyecto', 'Montaje de formato de especificaciones', 1),
('D1.21', 'Especificaciones de Edificación', 'Experiencia tu espacio presente vs futuro', 1),
('D1.21', 'Especificaciones de Edificación', 'Montaje de formato de especificaciones', 2),
('D1.22', 'Plano', 'Preparación y ajustes del archivo', 1),
('D1.22', 'Plano', 'Planta de urbanismo general con punteo', 2),
('D1.22', 'Plano', 'Cuadro de áreas', 3),
('D1.23', 'Manual', 'Anexo descriptivo y contractual', 1),
('D1.23', 'Manual', 'Planimetría', 2),
('D1.23', 'Manual', 'Presentación Indesing', 3),
('D1.24', 'Modelo Base + Topografía', 'Modelo Topográfico base', 1),
('D1.24', 'Planimetría Arquitectónica del Urbanismo', 'Planta de Urbanismo General', 1),
('D1.24', 'Planimetría Arquitectónica del Urbanismo', 'Planta de Etapa de Desarrollo', 2),
('D1.24', 'Planimetría Arquitectónica del Urbanismo', 'Cuadro de área de Urbanismo', 3),
('D1.25', 'Modelado Tridimensional Viewer 360 Zona complementaria', 'Diseño y modelado de Zona complementaria (planta)', 1),
('D1.25', 'Modelado Tridimensional Viewer 360 Zona complementaria', 'Diseño y modelado de Zona complementaria (fachada)', 2),
('D1.25', 'Modelado Tridimensional Viewer 360 Zona complementaria', 'Diseño y modelado de Zona complementaria (cubierta)', 3),
('D1.26', 'Planimetría Arquitectónica Elementos Complementarios', 'Planta Arquitectónica Elemento Complementario', 1),
('D1.26', 'Planimetría Arquitectónica Elementos Complementarios', 'Planta de cubierta Elemento Complementario', 2),
('D1.26', 'Planimetría Arquitectónica Elementos Complementarios', 'Secciones generales Elemento Complementario', 3),
('D1.26', 'Planimetría Arquitectónica Elementos Complementarios', 'Fachadas Elemento Complementario', 4),
('D1.26', 'Planimetría Arquitectónica Elementos Complementarios', 'Isométricos (Elemento complementario)', 5),
('D1.26', 'Planimetría Arquitectónica Elementos Complementarios', 'Cuadro de áreas (Elemento complementario)', 6),
('D1.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de edificación colectiva (planta)', 1),
('D1.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de edificación colectiva (fachada)', 2),
('D1.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño de obras complementarias edificación colectiva', 3),
('D1.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Integración a Topografía edificación colectiva', 4),
('D1.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Exportar Modelo edificación colectiva', 5),
('D1.4', 'Planimetría Arquitectónica del Urbanismo', 'Planta de Urbanismo General', 1),
('D1.4', 'Planimetría Arquitectónica del Urbanismo', 'Planta de Etapa de Desarrollo', 2),
('D1.4', 'Planimetría Arquitectónica del Urbanismo', 'Cuadro de área de Urbanismo', 3),
('D1.5', 'Planimetría Arquitectónica, Zona complementaria', 'Planta de Localización zona complementaria', 1),
('D1.5', 'Planimetría Arquitectónica, Zona complementaria', 'Planta Arquitectónica zona complementaria', 2),
('D1.5', 'Planimetría Arquitectónica, Zona complementaria', 'Secciones generales zona complementaria', 3),
('D1.5', 'Planimetría Arquitectónica, Zona complementaria', 'Fachadas generales zona complementaria', 4),
('D1.5', 'Planimetría Arquitectónica, Zona complementaria', 'Isométricos zona complementaria', 5),
('D1.5', 'Planimetría Arquitectónica, Zona complementaria', 'Cuadro de áreas zona complementaria', 6),
('D1.5', 'Planimetría Arquitectónica, Zona complementaria', 'General', 7),
('D1.6', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta de Localización (edificación colectiva)', 1),
('D1.6', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta Arquitectónica 1 (edificación colectiva)', 2),
('D1.6', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta de cubierta (edificación colectiva)', 3),
('D1.6', 'Planimetría arquitectónica escala variable según requerimiento.', 'Secciones generales (edificación colectiva)', 4),
('D1.6', 'Planimetría arquitectónica escala variable según requerimiento.', 'Fachadas (edificación colectiva)', 5),
('D1.6', 'Planimetría arquitectónica escala variable según requerimiento.', 'Isométricos (edificación colectiva)', 6),
('D1.6', 'Planimetría arquitectónica escala variable según requerimiento.', 'Cuadro de áreas (edificación colectiva)', 7),
('D1.6', 'Planimetría arquitectónica escala variable según requerimiento.', 'General', 8),
('D1.7', 'Modelo Tridimensional, Viewer 360 Escala Urbana', 'Preparativos del modelo', 1),
('D1.7', 'Modelo Tridimensional, Viewer 360 Escala Urbana', 'Planteamiento Vial', 2),
('D1.7', 'Modelo Tridimensional, detalle Escala Urbana', 'Planteamiento Vial', 1),
('D1.7', 'Modelo Tridimensional, detalle Escala Urbana', 'Ambientación', 2),
('D1.7', 'Modelo Tridimensional, detalle Escala Urbana', 'Integración a Topografía Edificación colectiva o terraza', 3),
('D1.8', 'Modelado Tridimensional Viewer 360 Zona complementaria', 'Diseño y modelado de Zona complementaria (planta)', 1),
('D1.8', 'Modelado Tridimensional Viewer 360 Zona complementaria', 'Diseño y modelado de Zona complementaria (fachada)', 2),
('D1.8', 'Modelado Tridimensional Viewer 360 Zona complementaria', 'Diseño y modelado de Zona complementaria (cubierta)', 3),
('D1.8', 'Modelado Tridimensional Viewer 360 Zona complementaria', 'Integración a Topografía zona complementaria', 4),
('D1.9', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de Edificación Colectiva (planta)', 1),
('D1.9', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de Edificación Colectiva (fachada)', 2),
('D1.9', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de Edificación Colectiva (cubierta)', 3),
('D1.9', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño de obras complementarias Edificación Colectiva', 4),
('D1.9', 'Modelo Tridimensional  a través de LINK en nube.', 'Integración a Topografía Edificación colectiva', 5),
('D1.9', 'Modelo Tridimensional  a través de LINK en nube.', 'Exportar Modelo Edificación colectiva', 6),
('D2.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de edificación en altura (planta)', 1),
('D2.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de edificación en altura (fachada)', 2),
('D2.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño de obras complementarias edificación en altura', 3),
('D2.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Integración a Topografía edificación en altura', 4),
('D2.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Exportar Modelo edificación en altura', 5),
('D2.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Socialización', 6),
('D2.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta de Localización (Edificación en Altura)', 1),
('D2.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta Arquitectónica 1 (Edificación en Altura)', 2),
('D2.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta de cubierta (Edificación en Altura)', 3),
('D2.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Secciones generales (Edificación en Altura)', 4),
('D2.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Fachadas (Edificación en Altura)', 5),
('D2.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Isométricos (Edificación en Altura)', 6),
('D2.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Cuadro de áreas (Edificación en Altura)', 7),
('D2.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'General', 8),
('D2.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de Edificación en altura (planta)', 1),
('D2.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de Edificación en altura (fachada)', 2),
('D2.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de Edificación en altura(cubierta)', 3),
('D2.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño de obras complementarias de Edificación en Altura', 4),
('D2.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Integración a Topografía de Edificación en altura', 5),
('D2.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Exportar Modelo de Edificación en Altura', 6),
('D2.4', 'Planimetría Arquitectónica de Edificación en Altura', 'Planta de Localización de Edificación en Altura', 1),
('D2.4', 'Planimetría Arquitectónica de Edificación en Altura', 'Planta Arquitectónica de Edificación en Altura', 2),
('D2.4', 'Planimetría Arquitectónica de Edificación en Altura', 'Planta de cubierta de Edificación en Altura', 3),
('D2.4', 'Planimetría Arquitectónica de Edificación en Altura', 'Secciones generales de Edificación en Altura', 4),
('D2.4', 'Planimetría Arquitectónica de Edificación en Altura', 'Fachadas de Edificación en altura', 5),
('D2.4', 'Planimetría Arquitectónica de Edificación en Altura', 'Isométricos (Edificación en Altura)', 6),
('D2.4', 'Planimetría Arquitectónica de Edificación en Altura', 'Cuadro de áreas (Edificación en altura)', 7),
('D2.5', 'Especificaciones de Edificación en Altura', 'Especificación general de los materiales a implementar', 1),
('D2.5', 'Especificaciones de Edificación en Altura', 'Montaje de formato de especificaciones', 2),
('D2.6', 'Modelo Tridimensional  a través de LINK en nube.', 'Preparativos del modelo', 1),
('D2.6', 'Modelo Tridimensional  a través de LINK en nube.', 'Detallar el modelo', 2),
('D2.7', 'Planimetría Arquitectónica de Detalle (Acabados en muros)', 'Detalle de Tipos de acabados en muros', 1),
('D2.7', 'Planimetría Arquitectónica de Detalle (Borde de losa)', 'Detalle de borde de losa', 1),
('D2.7', 'Planimetría Arquitectónica de Detalle (Carpintería)', 'Detalle de Funcionamiento y composición de carpintería', 1),
('D2.7', 'Planimetría Arquitectónica de Detalle (Cielos)', 'Detalle de iluminación', 1),
('D2.7', 'Planimetría Arquitectónica de Detalle (Cubiertas y pérgolas)', 'Detalle de elementos especiales', 1),
('D2.7', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de iluminación', 1),
('D2.7', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de modulación y tipos de cielo', 2),
('D2.7', 'Planimetría Arquitectónica de Detalle (Pisos)', 'Detalle de modulación y tipos de piso', 1),
('D2.7', 'Planimetría Arquitectónica de Detalle (Puertas y Ventanas)', 'Detalle de Funcionamiento y composición de puertas y ventanas', 1),
('D2.8', 'Especificaciones de Edificación', 'Montaje de formato de especificaciones', 1),
('D3.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de edificación colectiva (planta)', 1),
('D3.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de edificación colectiva (fachada)', 2),
('D3.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño de obras complementarias edificación colectiva', 3),
('D3.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Integración a Topografía edificación colectiva', 4),
('D3.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Exportar Modelo edificación colectiva', 5),
('D3.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Socialización', 6),
('D3.10', 'Ficha de lote', 'Gestión documental y creación de canales', 1),
('D3.10', 'Ficha de lote', 'Recolección de insumos preliminares', 2),
('D3.10', 'Ficha de lote', 'Análisis normativo', 3),
('D3.10', 'Ficha de lote', 'Análisis Bioblimático', 4),
('D3.10', 'Ficha de lote', 'Visita inicial al lote o análisis de modelo preexistente', 5),
('D3.10', 'Ficha de lote', 'Estudio de aprovechamiento', 6),
('D3.10', 'Ficha de lote', 'Ficha Resumen', 7),
('D3.11', 'Ficha de lote', 'Gestión documental y creación de canales', 1),
('D3.11', 'Ficha de lote', 'Recolección de insumos preliminares', 2),
('D3.11', 'Ficha de lote', 'Análisis normativo', 3),
('D3.11', 'Ficha de lote', 'Análisis Bioblimático', 4),
('D3.11', 'Ficha de lote', 'Montaje de Ficha Resumen', 5),
('D3.11', 'Ficha de lote', 'Socialización', 6),
('D3.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta de Localización (Vivienda Campestre)', 1),
('D3.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta Arquitectónica 1 (Vivienda Campestre)', 2),
('D3.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta de cubierta (Vivienda Campestre)', 3),
('D3.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Secciones generales (Vivienda Campestre)', 4),
('D3.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Fachadas (Vivienda Campestre)', 5),
('D3.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Isométricos (Vivienda Campestre)', 6),
('D3.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Cuadro de áreas (Vivienda Campestre)', 7),
('D3.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'General', 8),
('D3.3', 'Especificaciones de Vivienda Campestre', 'Montaje de formato de especificaciones', 1),
('D3.3', 'Especificaciones de Vivienda Campestre', 'Especificación general de los materiales a implementar', 2),
('D3.4', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de Vivienda Campestre (planta)', 1),
('D3.4', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de Vivienda Campestre (fachada)', 2),
('D3.4', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de Vivienda Campestre (cubierta)', 3),
('D3.4', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño de obras complementarias de Vivienda Campestre', 4),
('D3.4', 'Modelo Tridimensional  a través de LINK en nube.', 'Integración a Topografía de Vivienda Campestre', 5),
('D3.4', 'Modelo Tridimensional  a través de LINK en nube.', 'Exportar Modelo de Vivienda Campestre', 6),
('D3.5', 'Planimetría Arquitectónica de Vivienda Campestre', 'Planta de Localización de Vivienda Campestre', 1),
('D3.5', 'Planimetría Arquitectónica de Vivienda Campestre', 'Planta Arquitectónica de Vivienda Campestre', 2),
('D3.5', 'Planimetría Arquitectónica de Vivienda Campestre', 'Planta de cubierta de Vivienda Campestre', 3),
('D3.5', 'Planimetría Arquitectónica de Vivienda Campestre', 'Secciones generales de Vivienda Campestre', 4),
('D3.5', 'Planimetría Arquitectónica de Vivienda Campestre', 'Fachadas de Vivienda Campestre', 5),
('D3.5', 'Planimetría Arquitectónica de Vivienda Campestre', 'Isométricos (Vivienda Campestre)', 6),
('D3.5', 'Planimetría Arquitectónica de Vivienda Campestre', 'Cuadro de áreas (Vivienda Campestre)', 7),
('D3.6', 'Experiencia de replanteo de espacios de la vivienda 1:1 en lote', 'Preparativos de actividades', 1),
('D3.6', 'Experiencia de replanteo de espacios de la vivienda 1:1 en lote', 'Replanteo en campo', 2),
('D3.6', 'Experiencia de replanteo de espacios de la vivienda 1:1 en lote', 'Generar y participar de experiencia en campo', 3),
('D3.6', 'Experiencia de replanteo de espacios de la vivienda 1:1 en lote', 'Modificaciones en Modelo', 4),
('D3.7', 'Modelo Tridimensional  a través de LINK en nube.', 'Preparativos del modelo', 1),
('D3.7', 'Modelo Tridimensional  a través de LINK en nube.', 'Detallar el modelo', 2),
('D3.8', 'Planimetría Arquitectónica de Detalle (Acabados en muros)', 'Detalle de Tipos de acabados en muros', 1),
('D3.8', 'Planimetría Arquitectónica de Detalle (Borde de losa)', 'Detalle de borde de losa', 1),
('D3.8', 'Planimetría Arquitectónica de Detalle (Carpintería)', 'Detalle de Funcionamiento y composición de carpintería', 1),
('D3.8', 'Planimetría Arquitectónica de Detalle (Cielos)', 'Detalle de iluminación', 1),
('D3.8', 'Planimetría Arquitectónica de Detalle (Cubiertas y pérgolas)', 'Detalle de elementos especiales', 1),
('D3.8', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de iluminación', 1),
('D3.8', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de modulación y tipos de cielo', 2),
('D3.8', 'Planimetría Arquitectónica de Detalle (Pisos)', 'Detalle de modulación y tipos de piso', 1),
('D3.8', 'Planimetría Arquitectónica de Detalle (Puertas y Ventanas)', 'Detalle de Funcionamiento y composición de puertas y ventanas', 1),
('D3.9', 'Especificaciones de Edificación', 'Montaje de formato de especificaciones', 1),
('D4.1', 'Cabida Preliminar', 'Definición del proyecto', 1),
('D4.1', 'Modelo Tridimensional del Estado Preliminar', 'Montaje de modelo 3D Básico', 1),
('D4.1', 'Paquete de planos Arquitectónicos del estado preliminar', 'Montaje de Layout 2D', 1),
('D4.1', 'Paquete de planos Arquitectónicos del estado preliminar', 'Cuadro de áreas', 2),
('D4.1', 'Presentación de concepto espacial, determinantes y cabida', 'Conceptualización', 1),
('D4.1', 'Presentación de concepto espacial, determinantes y cabida', 'Montaje de modelo 3D Básico', 2),
('D4.1', 'Presentación de conceptualización e ideación general', 'Montaje de presentación', 1),
('D4.1', 'Presentación de conceptualización e ideación general', 'Montaje de modelo 3D Básico', 2),
('D4.2', 'Paquete de planimetría técnica de stand + Viewer 360', 'Materiales', 1),
('D4.2', 'Paquete de planimetría técnica de stand + Viewer 360', 'Mobiliario a la medida', 2),
('D4.2', 'Paquete de planimetría técnica de stand + Viewer 360', 'Señaletica y comunicación visual', 3),
('D4.2', 'Paquete de planimetría técnica de stand + Viewer 360', 'Detalle de señaletica', 4),
('D4.2', 'Paquete de planimetría técnica de stand + Viewer 360', 'Detalle de Iluminación', 5),
('D4.2', 'Paquete de planimetría técnica de stand + Viewer 360', 'Vitrinismo, Merchandising y exhibición de productos', 6),
('D4.2', 'Paquete de planimetría técnica de stand + Viewer 360', 'Logística de experiencia', 7),
('D4.2', 'Paquete de planimetría técnica de stand + Viewer 360', 'Cantidades de Obra', 8),
('D4.3', 'Extracción de cantidades de obra', 'Extraer cantidades de obra (base para presupuesto)', 1),
('D4.3', 'Presupuesto', 'Construcción de archivo general', 1),
('D4.3', 'Presupuesto', 'Cotizaciones con proveedores', 2),
('D4.3', 'Presupuesto', 'Archivos de soporte y guías para la construcción', 3),
('D4.3', 'Presupuesto', 'Análisis de precios unitarios', 4),
('D4.3', 'Presupuesto', 'Cronograma', 5),
('D6.1', 'Cabida Preliminar', 'Definición del proyecto', 1),
('D6.1', 'Modelo Tridimensional del Estado Preliminar', 'Visita inicial al espacio', 1),
('D6.1', 'Modelo Tridimensional del Estado Preliminar', 'Montaje de modelo 3D Básico', 2),
('D6.1', 'Paquete de planos Arquitectónicos del estado preliminar', 'Montaje de paquete de planos básicos', 1),
('D6.1', 'Paquete de planos Arquitectónicos del estado preliminar', 'Cuadro de áreas', 2),
('D6.1', 'Paquete de planos Arquitectónicos del estado preliminar', 'Experiencia de presentación de propuesta', 3),
('D6.1', 'Paquete de planos Arquitectónicos del estado preliminar', 'Cuadro de áreas o especificaciones generales', 4),
('D6.1', 'Presentación de concepto espacial, determinantes y cabida', 'Conceptualización', 1),
('D6.1', 'Presentación de concepto espacial, determinantes y cabida', 'Propuesta de cabida y programa', 2),
('D6.1', 'Presentación de concepto espacial, determinantes y cabida', 'Montaje de modelo 3D Básico de propuesta', 3),
('D6.2', 'Presentación de conceptualización e ideación general', 'Taller de diseño', 1),
('D6.2', 'Presentación de conceptualización e ideación general', 'Montaje del Look and Feel', 2),
('D6.2', 'Presentación de conceptualización e ideación general', 'Materialización del Look & feel en imágenes', 3),
('D6.2', 'Presentación de conceptualización e ideación general', 'Reunión de presentación', 4),
('D6.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Preparativos del modelo', 1),
('D6.3', 'Modelo Tridimensional  a través de LINK en nube.', 'Detallar el modelo', 2),
('D6.4', 'Planimetría Arquitectónica de Detalle (Acabados en muros)', 'Detalle de Tipos de acabados en muros', 1),
('D6.4', 'Planimetría Arquitectónica de Detalle (Carpintería)', 'Detalle de Funcionamiento y composición de carpintería', 1),
('D6.4', 'Planimetría Arquitectónica de Detalle (Cielos)', 'Detalle de iluminación', 1),
('D6.4', 'Planimetría Arquitectónica de Detalle (Cubiertas y pérgolas)', 'Detalle de elementos característicos de la propuesta', 1),
('D6.4', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de iluminación', 1),
('D6.4', 'Planimetría Arquitectónica de Detalle (Iluminación)', 'Detalle de modulación y tipos de cielo', 2),
('D6.4', 'Planimetría Arquitectónica de Detalle (Pisos)', 'Detalle de modulación y tipos de piso', 1),
('D6.4', 'Planimetría Arquitectónica de Detalle (Puertas y Ventanas)', 'Detalle de Funcionamiento y composición de puertas y ventanas', 1),
('D6.5', 'Especificaciones, experiencia de compra y cantidades de obra', 'Experiencia de compras', 1),
('D6.5', 'Especificaciones, experiencia de compra y cantidades de obra', 'Especificación general de los materiales a implementar', 2),
('D6.5', 'Especificaciones, experiencia de compra y cantidades de obra', 'Montaje de formato de especificaciones', 3),
('D6.6', '3 Renders Interiores', 'Renders', 1),
('D6.6', 'Cabida Preliminar', 'Definición del proyecto', 1),
('D6.6', 'Modelo Tridimensional del Estado Preliminar', 'Montaje de modelo 3D Básico', 1),
('D6.6', 'Paquete de planos Arquitectónicos del estado preliminar', 'Montaje de paquete de planos básicos', 1),
('D6.6', 'Paquete de planos Arquitectónicos del estado preliminar', 'Cuadro de áreas', 2),
('D6.6', 'Paquete de planos Arquitectónicos del estado preliminar', 'Experiencia de presentación de propuesta', 3),
('D6.6', 'Planimetría', 'Insumo de planimetría', 1),
('D6.6', 'Presentación de concepto espacial, determinantes y cabida', 'Visita inicial al espacio', 1),
('D6.6', 'Presentación de concepto espacial, determinantes y cabida', 'Propuesta de cabida y programa', 2),
('D6.6', 'Presentación de concepto espacial, determinantes y cabida', 'Conceptualización', 3),
('D6.6', 'Viewer 360', 'Modelo Tridimensional', 1),
('D6.7', '3 Renders Interiores', 'Renders', 1),
('D6.7', 'Cabida Preliminar', 'Definición del proyecto', 1),
('D6.7', 'Modelo Tridimensional del Estado Preliminar', 'Montaje de modelo 3D Básico', 1),
('D6.7', 'Paquete de planos Arquitectónicos del estado preliminar', 'Montaje de paquete de planos básicos', 1),
('D6.7', 'Paquete de planos Arquitectónicos del estado preliminar', 'Cuadro de áreas', 2),
('D6.7', 'Paquete de planos Arquitectónicos del estado preliminar', 'Experiencia de presentación de propuesta', 3),
('D6.7', 'Planimetría', 'Insumo de planimetría', 1),
('D6.7', 'Presentación de concepto espacial, determinantes y cabida', 'Visita inicial al espacio', 1),
('D6.7', 'Presentación de concepto espacial, determinantes y cabida', 'Registro de Mobiliario', 2),
('D6.7', 'Presentación de concepto espacial, determinantes y cabida', 'Propuesta de cabida y programa', 3),
('D6.7', 'Presentación de concepto espacial, determinantes y cabida', 'Conceptualización', 4),
('D6.7', 'Viewer 360', 'Modelo Tridimensional', 1),
('D7.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de edificación colectiva (planta)', 1),
('D7.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño y modelado de edificación colectiva (fachada)', 2),
('D7.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Diseño de obras complementarias edificación colectiva', 3),
('D7.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Integración a Topografía edificación colectiva', 4),
('D7.1', 'Modelo Tridimensional  a través de LINK en nube.', 'Exportar Modelo edificación colectiva', 5),
('D7.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta de Localización (Vivienda Campestre)', 1),
('D7.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta Arquitectónica 1 (Vivienda Campestre)', 2),
('D7.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Planta de cubierta (Vivienda Campestre)', 3),
('D7.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Secciones generales (Vivienda Campestre)', 4),
('D7.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Fachadas (Vivienda Campestre)', 5),
('D7.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Isométricos (Vivienda Campestre)', 6),
('D7.2', 'Planimetría arquitectónica escala variable según requerimiento.', 'Cuadro de áreas (Vivienda Campestre)', 7),
]


class Command(BaseCommand):
    help = "Carga actividades clave de servicios D.sign desde el Excel maestro."

    def handle(self, *args, **options):
        from apps.services.models import Deliverable, KeyActivity, ServiceTemplate

        created_count = 0
        skipped_count = 0
        missing = []

        for code, deliverable_name, activity_name, order in DATA:
            # Normalizar espacios múltiples (el Excel puede tener doble espacio)
            deliverable_name = " ".join(deliverable_name.split())
            activity_name = " ".join(activity_name.split())

            try:
                service = ServiceTemplate.objects.get(code=code)
            except ServiceTemplate.DoesNotExist:
                missing.append(f"{code}")
                skipped_count += 1
                continue

            try:
                deliverable = service.deliverables.get(name=deliverable_name)
            except Deliverable.DoesNotExist:
                missing.append(f"{code}/{deliverable_name[:40]}")
                skipped_count += 1
                continue

            _, created = KeyActivity.objects.get_or_create(
                deliverable=deliverable,
                name=activity_name,
                defaults={"order": order},
            )
            if created:
                created_count += 1

        if missing:
            self.stdout.write(
                self.style.WARNING(
                    f"  Entregables no encontrados ({len(missing)} omitidos): "
                    + ", ".join(sorted(set(missing))[:10])
                    + ("..." if len(set(missing)) > 10 else "")
                )
            )

        self.stdout.write(
            self.style.SUCCESS(
                f"✓ Actividades clave: {created_count} creadas, {skipped_count} omitidas."
            )
        )
