# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('DELIVERABLE', 'Entregable'), ('SUPPORT', 'Soporte'), ('CONTRACT', 'Contrato'), ('INVOICE', 'Factura'), ('OTHER', 'Otro')], default='DELIVERABLE', max_length=50, verbose_name='tipo de documento')),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('access_link', models.URLField(blank=True, help_text='Enlace a Google Drive u otro servicio de almacenamiento.', verbose_name='enlace de acceso')),
                ('file', models.FileField(blank=True, upload_to='documents/%Y/%m/', verbose_name='archivo')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='fecha de entrega')),
                ('approval_date', models.DateField(blank=True, null=True, verbose_name='fecha de aprobacion')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='proyecto')),
                ('service_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.serviceinstance', verbose_name='instancia de servicio')),
            ],
            options={
                'verbose_name': 'documento de proyecto',
                'verbose_name_plural': 'documentos de proyecto',
                'ordering': ['-created_at'],
            },
        ),
    ]
