# Generated by Django 5.2.12 on 2026-04-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='document_type',
            field=models.CharField(choices=[('QUOTATION', 'Cotización'), ('CONTRACT', 'Contrato'), ('DELIVERABLE', 'Entregable'), ('SUPPORT', 'Soporte'), ('INVOICE', 'Factura'), ('OTHER', 'Otro')], default='DELIVERABLE', max_length=50, verbose_name='tipo de documento'),
        ),
    ]
