# Generated by Django 5.1.15 on 2026-04-06 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_uploaded_by'),
        ('services', '0003_servicetemplate_operative_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectdocument',
            name='audience',
            field=models.CharField(choices=[('INTERNAL', 'Interno'), ('CLIENT', 'Cliente')], default='INTERNAL', max_length=10, verbose_name='audiencia'),
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('QUOTATION', 'Cotización'), ('CONTRACT', 'Contrato'), ('DELIVERABLE', 'Entregable'), ('SUPPORT', 'Soporte'), ('INVOICE', 'Factura'), ('OTHER', 'Otro')], max_length=50, verbose_name='tipo de documento')),
                ('name', models.CharField(max_length=300, verbose_name='nombre / descripción')),
                ('audience', models.CharField(choices=[('INTERNAL', 'Interno'), ('CLIENT', 'Cliente')], default='INTERNAL', max_length=10, verbose_name='audiencia')),
                ('is_required', models.BooleanField(default=True, verbose_name='requerido')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('project_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='services.projectcategory', verbose_name='categoría de proyecto')),
            ],
            options={
                'verbose_name': 'plantilla de documento',
                'verbose_name_plural': 'plantillas de documentos',
                'ordering': ['project_category', 'document_type', 'name'],
            },
        ),
    ]
