# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatisfactionMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_date', models.DateField(verbose_name='fecha de medición')),
                ('observed_emotion_pct', models.DecimalField(decimal_places=2, default=0, help_text='Emoción Observada', max_digits=5, verbose_name='emoción observada')),
                ('spontaneous_phrase_pct', models.DecimalField(decimal_places=2, default=0, help_text='Frase Espontánea', max_digits=5, verbose_name='frase espontánea')),
                ('audio_video_link', models.URLField(blank=True, help_text='Audio | Video', verbose_name='audio | video')),
                ('symbolic_object_pct', models.DecimalField(decimal_places=2, default=0, help_text='Objeto Simbólico', max_digits=5, verbose_name='objeto simbólico')),
                ('cve_score', models.DecimalField(decimal_places=2, default=0, help_text='Puntuación CVE', max_digits=5, verbose_name='puntuación CVE')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.milestone', verbose_name='hito')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfaction_measurements', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'medición de satisfacción',
                'verbose_name_plural': 'mediciones de satisfacción',
                'ordering': ['-measurement_date'],
            },
        ),
        migrations.CreateModel(
            name='SatisfactionSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('general_sensation', models.DecimalField(decimal_places=2, default=0, help_text='Sensación general del proceso', max_digits=5, verbose_name='sensación general del proceso')),
                ('clarity_and_support', models.DecimalField(decimal_places=2, default=0, help_text='Claridad y acompañamiento', max_digits=5, verbose_name='claridad y acompañamiento')),
                ('personal_effort', models.DecimalField(decimal_places=2, default=0, help_text='Esfuerzo personal', max_digits=5, verbose_name='esfuerzo personal')),
                ('team_relationship', models.DecimalField(decimal_places=2, default=0, help_text='Relación con el equipo', max_digits=5, verbose_name='relación con el equipo')),
                ('confidence', models.DecimalField(decimal_places=2, default=0, help_text='Confianza', max_digits=5, verbose_name='confianza')),
                ('perceived_value', models.DecimalField(decimal_places=2, default=0, help_text='Valor percibido', max_digits=5, verbose_name='valor percibido')),
                ('total_score_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='puntuación total (%)')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('measurement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='satisfaction.satisfactionmeasurement', verbose_name='medición')),
            ],
            options={
                'verbose_name': 'encuesta de asertividad',
                'verbose_name_plural': 'encuestas de asertividad',
            },
        ),
    ]
