from django.urls import path

from apps.projects import views

app_name = "projects"

urlpatterns = [
    # Projects
    path(
        "",
        views.ProjectListView.as_view(),
        name="list",
    ),
    path(
        "<int:pk>/",
        views.ProjectDetailView.as_view(),
        name="detail",
    ),
    path(
        "crear/",
        views.ProjectCreateView.as_view(),
        name="create",
    ),
    path(
        "<int:pk>/editar/",
        views.ProjectUpdateView.as_view(),
        name="update",
    ),
    # Phase services
    path(
        "<int:pk>/fases/<int:phase_pk>/servicios/",
        views.ServiceInstanceListView.as_view(),
        name="phase_services",
    ),
    path(
        "<int:pk>/servicios/<int:si_pk>/editar/",
        views.ServiceInstanceUpdateView.as_view(),
        name="service_update",
    ),
    # Service create / delete (Bloque 2)
    path(
        "<int:pk>/fases/<int:phase_pk>/servicios/crear/",
        views.ServiceInstanceCreateView.as_view(),
        name="service_create",
    ),
    path(
        "<int:pk>/servicios/<int:si_pk>/eliminar/",
        views.ServiceInstanceDeleteView.as_view(),
        name="service_delete",
    ),
    # Prerequisites (HTMX)
    path(
        "<int:pk>/prerequisitos/crear/",
        views.PrerequisiteCreateView.as_view(),
        name="prerequisite_create",
    ),
    path(
        "<int:pk>/prerequisitos/<int:prereq_pk>/toggle/",
        views.PrerequisiteToggleView.as_view(),
        name="prerequisite_toggle",
    ),
    path(
        "<int:pk>/prerequisitos/<int:prereq_pk>/eliminar/",
        views.PrerequisiteDeleteView.as_view(),
        name="prerequisite_delete",
    ),
    # Milestones (HTMX) - Bloque 1
    path(
        "<int:pk>/hitos/crear/",
        views.MilestoneCreateView.as_view(),
        name="milestone_create",
    ),
    path(
        "<int:pk>/hitos/<int:milestone_pk>/eliminar/",
        views.MilestoneDeleteView.as_view(),
        name="milestone_delete",
    ),
    # Schedule services (HTMX)
    path(
        "<int:pk>/cronograma/servicios/agregar/",
        views.ScheduleServiceCreateView.as_view(),
        name="schedule_service_create",
    ),
    path(
        "<int:pk>/cronograma/servicios/<int:si_pk>/eliminar/",
        views.ScheduleServiceDeleteView.as_view(),
        name="schedule_service_delete",
    ),
    path(
        "<int:pk>/cronograma/calcular-fecha-fin/",
        views.CalcServiceEndDateView.as_view(),
        name="schedule_calc_end_date",
    ),
    path(
        "<int:pk>/cronograma/responsables/",
        views.ScheduleServiceResponsiblesView.as_view(),
        name="schedule_service_responsibles",
    ),
    path(
        "<int:pk>/cronograma/servicios/arbol/",
        views.ScheduleServiceTreeView.as_view(),
        name="schedule_service_tree",
    ),
    path(
        "<int:pk>/cronograma/servicios/<int:si_pk>/acciones/",
        views.ScheduleServiceActionsView.as_view(),
        name="schedule_service_actions",
    ),
    path(
        "<int:pk>/cronograma/servicios/<int:si_pk>/acciones/<int:action_pk>/toggle/",
        views.ActionToggleView.as_view(),
        name="action_toggle",
    ),
    path(
        "<int:pk>/cronograma/servicios/<int:si_pk>/acciones/<int:action_pk>/avance/",
        views.ActionProgressLogView.as_view(),
        name="action_progress_log",
    ),
    path(
        "<int:pk>/cronograma/servicios/<int:si_pk>/acciones/<int:action_pk>/historial/",
        views.ActionProgressHistoryView.as_view(),
        name="action_progress_history",
    ),
    path(
        "<int:pk>/cronograma/servicios/<int:si_pk>/aprobar/",
        views.ServiceApprovalView.as_view(),
        name="service_approval",
    ),
    path(
        "<int:pk>/cronograma/tabla/",
        views.ScheduleTableView.as_view(),
        name="schedule_table",
    ),
    path(
        "<int:pk>/cronograma/servicios/<int:si_pk>/editar/",
        views.ScheduleServiceEditView.as_view(),
        name="schedule_service_edit",
    ),
    # Validation (HTMX)
    path(
        "<int:pk>/validar-asignacion/",
        views.ValidateAssignmentView.as_view(),
        name="validate_assignment",
    ),
    # Scopes (HTMX)
    path(
        "<int:pk>/alcances/crear/",
        views.ScopeCreateView.as_view(),
        name="scope_create",
    ),
    path(
        "<int:pk>/alcances/<int:scope_pk>/editar/",
        views.ScopeEditView.as_view(),
        name="scope_edit",
    ),
    path(
        "<int:pk>/alcances/<int:scope_pk>/cancelar/",
        views.ScopeCancelEditView.as_view(),
        name="scope_cancel_edit",
    ),
    path(
        "<int:pk>/alcances/<int:scope_pk>/eliminar/",
        views.ScopeDeleteView.as_view(),
        name="scope_delete",
    ),
    # Clients
    path(
        "clientes/",
        views.ClientListView.as_view(),
        name="client_list",
    ),
    path(
        "clientes/crear/",
        views.ClientCreateView.as_view(),
        name="client_create",
    ),
    # Prerequisite: load template (HTMX)
    path(
        "<int:pk>/prerequisitos/cargar-plantilla/",
        views.PrerequisiteLoadTemplateView.as_view(),
        name="prerequisite_load_template",
    ),
    # PrerequisiteTemplate CRUD (Maestros)
    path(
        "maestros/plantillas-prerequisitos/",
        views.PrerequisiteTemplateListView.as_view(),
        name="prereq_template_list",
    ),
    path(
        "maestros/plantillas-prerequisitos/crear/",
        views.PrerequisiteTemplateCreateView.as_view(),
        name="prereq_template_create",
    ),
    path(
        "maestros/plantillas-prerequisitos/<int:pk>/editar/",
        views.PrerequisiteTemplateUpdateView.as_view(),
        name="prereq_template_update",
    ),
    path(
        "maestros/plantillas-prerequisitos/<int:pk>/eliminar/",
        views.PrerequisiteTemplateDeleteView.as_view(),
        name="prereq_template_delete",
    ),
]
