# Generated by Django 5.1.15 on 2026-03-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='empresa')),
                ('nit', models.CharField(blank=True, help_text='Número de identificación tributaria (para cruce con Loggro).', max_length=20, verbose_name='NIT')),
                ('relationship_type', models.CharField(choices=[('CLIENTE', 'Cliente'), ('PROSPECTO', 'Prospecto'), ('GROWTH_PARTNER', 'Growth Partner'), ('EMBAJADOR', 'Embajador'), ('PROVEEDOR', 'Proveedor'), ('EQUIPO_INTERNO', 'Equipo Interno'), ('ALIADO_ESTRATEGICO', 'Aliado Estratégico'), ('OTRO', 'Otro')], max_length=30, verbose_name='tipo de relación')),
                ('client_category', models.CharField(blank=True, choices=[('BLACK', 'Black'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('SELECT', 'Select')], help_text='Solo aplica cuando el tipo de relación es Cliente.', max_length=10, verbose_name='categoría de cliente')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='ciudad')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('legacy_client_id', models.IntegerField(blank=True, editable=False, null=True, verbose_name='ID de cliente legacy')),
            ],
            options={
                'verbose_name': 'tercero',
                'verbose_name_plural': 'terceros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThirdPartyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('role', models.CharField(blank=True, max_length=100, verbose_name='cargo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('is_primary', models.BooleanField(default=False, verbose_name='contacto principal')),
                ('third_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='terceros.thirdparty', verbose_name='tercero')),
            ],
            options={
                'verbose_name': 'contacto de tercero',
                'verbose_name_plural': 'contactos de tercero',
                'ordering': ['-is_primary', 'name'],
            },
        ),
    ]
