# Generated by Django 5.1.15 on 2026-05-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_migrate_clients_to_thirdparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='document_type',
            field=models.CharField(blank=True, choices=[('NIT', 'NIT'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], default='NIT', max_length=15, verbose_name='tipo de documento'),
        ),
        migrations.AlterField(
            model_name='thirdparty',
            name='nit',
            field=models.CharField(blank=True, help_text='Número de documento (NIT, cédula, etc.) para cruce con Loggro.', max_length=20, verbose_name='número de documento'),
        ),
    ]
