# Generated by Django 5.2.12 on 2026-05-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0003_thirdparty_document_type_alter_thirdparty_nit'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='person_type',
            field=models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], default='NATURAL', max_length=10, verbose_name='tipo de persona'),
        ),
    ]
