# Generated by Django 5.2.12 on 2026-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0004_thirdparty_person_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdparty',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='dirección'),
        ),
    ]
