# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColombianHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True, verbose_name='fecha')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
            ],
            options={
                'verbose_name': 'festivo colombiano',
                'verbose_name_plural': 'festivos colombianos',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProfitabilitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milestone_name', models.CharField(help_text='Ej: "Entrega 1", "Entrega 2"', max_length=200, verbose_name='nombre del hito')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor')),
                ('months_invested', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='meses invertidos')),
                ('analysis_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costos de analisis')),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costos totales')),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='gastos')),
                ('cost_plus_expenses_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costo + gastos mensual')),
                ('cost_plus_expenses_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costo + gastos total')),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ingresos')),
                ('utility', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='utilidad')),
                ('margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='% margen')),
                ('utility_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='utilidad mensual')),
                ('margin_monthly_pct', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='% margen mensual')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verificado')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profitability_summaries', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'resumen de rentabilidad',
                'verbose_name_plural': 'resumenes de rentabilidad',
                'ordering': ['project', 'milestone_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.CharField(help_text='Ej: "Anticipo", "Abono 2", "Pago Final"', max_length=200, verbose_name='concepto')),
                ('proposed_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor propuesto')),
                ('iva_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor IVA')),
                ('incidence_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% incidencia')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('INVOICED', 'Facturado'), ('COLLECTED', 'Recaudado'), ('OVERDUE', 'Vencido')], default='PENDING', max_length=20, verbose_name='estado')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% descuento')),
                ('discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor descuento')),
                ('executed_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor ejecutado')),
                ('billing_date', models.DateField(blank=True, null=True, verbose_name='fecha de facturación')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='número de factura')),
                ('invoice_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor factura')),
                ('collection_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor recaudo')),
                ('collection_date', models.DateField(blank=True, null=True, verbose_name='fecha de recaudo')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='diferencia')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_milestones', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'hito de pago',
                'verbose_name_plural': 'hitos de pago',
                'ordering': ['project', 'incidence_pct'],
            },
        ),
    ]
