# Generated by Django 5.1.15 on 2026-03-08 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0001_initial'),
        ('imports', '0002_alter_importjob_source_type'),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.CharField(max_length=30, unique=True, verbose_name='código de cuenta')),
                ('name', models.CharField(max_length=300, verbose_name='nombre')),
                ('account_type', models.CharField(blank=True, choices=[('ASSET', 'Activo'), ('LIABILITY', 'Pasivo'), ('EQUITY', 'Patrimonio'), ('REVENUE', 'Ingreso'), ('EXPENSE', 'Gasto'), ('COST', 'Costo')], max_length=20, verbose_name='tipo de cuenta')),
                ('is_active', models.BooleanField(default=True, verbose_name='activa')),
            ],
            options={
                'verbose_name': 'cuenta contable',
                'verbose_name_plural': 'cuentas contables',
                'ordering': ['account_code'],
            },
        ),
        migrations.CreateModel(
            name='CostAllocationPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='Formato "YYYY-MM".', max_length=7, unique=True, verbose_name='periodo')),
                ('start_date', models.DateField(verbose_name='fecha inicio')),
                ('end_date', models.DateField(verbose_name='fecha fin')),
                ('is_closed', models.BooleanField(default=False, verbose_name='cerrado')),
                ('total_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='costos totales')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
            ],
            options={
                'verbose_name': 'periodo de asignación',
                'verbose_name_plural': 'periodos de asignación',
                'ordering': ['-period'],
            },
        ),
        migrations.CreateModel(
            name='CostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_type', models.CharField(choices=[('OPERATIVE', 'Tiempo Operativo'), ('STRATEGIC', 'Tiempo Estratégico'), ('DIRECT', 'Costo Directo')], max_length=20, verbose_name='tipo de costo')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='monto asignado')),
                ('allocation_pct', models.DecimalField(decimal_places=4, default=0, max_digits=7, verbose_name='% asignación')),
                ('source_description', models.CharField(blank=True, max_length=200, verbose_name='descripción de origen')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_allocations', to='projects.project', verbose_name='proyecto')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='financials.costallocationperiod', verbose_name='periodo')),
            ],
            options={
                'verbose_name': 'asignación de costos',
                'verbose_name_plural': 'asignaciones de costos',
                'ordering': ['period', 'project'],
            },
        ),
        migrations.CreateModel(
            name='CostCenterMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center_code', models.CharField(max_length=50, unique=True, verbose_name='código centro de costo')),
                ('cost_center_name', models.CharField(max_length=200, verbose_name='nombre centro de costo')),
                ('business_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.businessunit', verbose_name='unidad de negocio')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_center_mappings', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'mapeo de centro de costo',
                'verbose_name_plural': 'mapeos de centros de costo',
                'ordering': ['cost_center_code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_date', models.DateField(verbose_name='fecha documento')),
                ('document_type', models.CharField(blank=True, max_length=50, verbose_name='tipo documento')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='número documento')),
                ('third_party_nit', models.CharField(blank=True, max_length=50, verbose_name='NIT tercero')),
                ('third_party_name', models.CharField(blank=True, max_length=300, verbose_name='nombre tercero')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='débito')),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='crédito')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='saldo')),
                ('period', models.CharField(help_text='Formato "YYYY-MM".', max_length=7, verbose_name='periodo')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financials.accountingaccount', verbose_name='cuenta')),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_txns', to='imports.importjob', verbose_name='trabajo de importación')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='financials.costcentermapping', verbose_name='centro de costo')),
            ],
            options={
                'verbose_name': 'transacción contable',
                'verbose_name_plural': 'transacciones contables',
                'ordering': ['document_date', 'pk'],
                'indexes': [models.Index(fields=['period'], name='idx_acctxn_period'), models.Index(fields=['account', 'period'], name='idx_acctxn_acc_period')],
            },
        ),
    ]
