# Generated by Django 5.1.15 on 2026-04-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0002_accountingaccount_costallocationperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colombianholiday',
            name='holiday_type',
            field=models.CharField(choices=[('NATIONAL', 'Nacional'), ('COMPANY', 'CNTXT')], default='NATIONAL', max_length=10, verbose_name='tipo'),
        ),
    ]
