# Generated by Django 5.1.15 on 2026-04-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0003_add_holiday_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('monthly_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor mensual ($COP)')),
                ('hourly_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='valor por hora ($COP)')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'tipo de gasto operacional',
                'verbose_name_plural': 'tipos de gasto operacional',
                'ordering': ['name'],
            },
        ),
    ]
