# Generated by Django 5.1.15 on 2026-04-06 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0004_add_operational_expense_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationalexpensetype',
            name='hourly_value',
        ),
        migrations.RemoveField(
            model_name='operationalexpensetype',
            name='monthly_value',
        ),
    ]
