# Generated by Django 5.1.15 on 2026-04-24 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0005_remove_expense_type_values'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('category_type', models.CharField(choices=[('ingreso', 'Ingreso'), ('costo', 'Costo'), ('gasto', 'Gasto'), ('impuesto', 'Impuesto')], default='gasto', max_length=20, verbose_name='tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'categoría de gasto',
                'verbose_name_plural': 'categorías de gasto',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='operationalexpensetype',
            options={'ordering': ['subcategory__category__code', 'subcategory__code', 'name'], 'verbose_name': 'concepto de gasto', 'verbose_name_plural': 'conceptos de gasto'},
        ),
        migrations.AddField(
            model_name='operationalexpensetype',
            name='monthly_reference',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor mensual referencia ($COP)'),
        ),
        migrations.AddField(
            model_name='operationalexpensetype',
            name='vendor',
            field=models.CharField(blank=True, max_length=200, verbose_name='tercero / proveedor'),
        ),
        migrations.AlterField(
            model_name='operationalexpensetype',
            name='name',
            field=models.CharField(max_length=200, verbose_name='concepto'),
        ),
        migrations.CreateModel(
            name='ExpenseSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='financials.expensecategory', verbose_name='categoría')),
                ('operative_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_subcategories', to='organizations.operativeline', verbose_name='línea operativa (opcional)')),
            ],
            options={
                'verbose_name': 'subcategoría de gasto',
                'verbose_name_plural': 'subcategorías de gasto',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.AddField(
            model_name='operationalexpensetype',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_types', to='financials.expensesubcategory', verbose_name='subcategoría'),
        ),
    ]
