# Generated by Django 5.1.15 on 2026-04-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0006_expense_category_subcategory_hierarchy'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenterSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('cost_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='financials.costcentermapping', verbose_name='centro de costo')),
            ],
            options={
                'verbose_name': 'subcategoría de centro de costo',
                'verbose_name_plural': 'subcategorías de centros de costo',
                'ordering': ['cost_center__cost_center_code', 'code'],
                'unique_together': {('cost_center', 'code')},
            },
        ),
    ]
