# Generated by Django 5.1.15 on 2026-04-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financials', '0007_costcentersubcategory'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineAllocationWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quarter', models.CharField(help_text='Formato "YYYY-QN", ej. "2026-Q1".', max_length=7, verbose_name='trimestre')),
                ('weight_pct', models.DecimalField(decimal_places=2, help_text='Porcentaje del costo total asignado a esta línea. La suma de todas las líneas del trimestre debe ser 100.', max_digits=5, verbose_name='peso (%)')),
                ('is_manual', models.BooleanField(default=True, verbose_name='configurado manualmente')),
                ('operative_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocation_weights', to='organizations.operativeline', verbose_name='línea operativa')),
            ],
            options={
                'verbose_name': 'peso de línea por trimestre',
                'verbose_name_plural': 'pesos de líneas por trimestre',
                'ordering': ['quarter', 'operative_line__code'],
                'unique_together': {('quarter', 'operative_line')},
            },
        ),
    ]
