# Generated by Django 5.2.12 on 2026-03-20 11:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_third_party'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTimeDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_start', models.DateField(help_text='Lunes de la semana reportada.', verbose_name='inicio de semana')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SUBMITTED', 'Enviado')], default='DRAFT', max_length=20, verbose_name='estado')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envío')),
                ('notes', models.TextField(blank=True, verbose_name='notas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_distributions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'distribución semanal',
                'verbose_name_plural': 'distribuciones semanales',
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
        migrations.CreateModel(
            name='TimeDistributionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='porcentaje')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.project', verbose_name='proyecto')),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetracking.weeklytimedistribution', verbose_name='distribución')),
            ],
            options={
                'verbose_name': 'entrada de distribución',
                'verbose_name_plural': 'entradas de distribución',
                'ordering': ['-percentage'],
                'unique_together': {('distribution', 'project')},
            },
        ),
    ]
