# Generated by Django 5.2.12 on 2026-03-20 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_project_third_party'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.TextField(blank=True, verbose_name='token de acceso')),
                ('refresh_token', models.TextField(blank=True, verbose_name='token de refresco')),
                ('token_expiry', models.DateTimeField(blank=True, null=True, verbose_name='expiración del token')),
                ('calendar_id', models.CharField(default='primary', max_length=200, verbose_name='ID del calendario')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='última sincronización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_connection', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'conexión de Google Calendar',
                'verbose_name_plural': 'conexiones de Google Calendar',
            },
        ),
        migrations.CreateModel(
            name='ProjectKeywordMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('keyword', models.CharField(help_text='Si el título del evento contiene esta palabra, se asocia al proyecto.', max_length=100, verbose_name='palabra clave')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keyword_mappings', to='projects.project', verbose_name='proyecto')),
            ],
            options={
                'verbose_name': 'mapeo de palabra clave',
                'verbose_name_plural': 'mapeos de palabras clave',
                'ordering': ['project', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_event_id', models.CharField(max_length=255, verbose_name='ID del evento en Google')),
                ('title', models.CharField(max_length=500, verbose_name='título')),
                ('start_time', models.DateTimeField(verbose_name='inicio')),
                ('end_time', models.DateTimeField(verbose_name='fin')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='duración (horas)')),
                ('color_id', models.CharField(blank=True, max_length=20, verbose_name='color del evento')),
                ('match_method', models.CharField(choices=[('AUTO_NAME', 'Automático (nombre)'), ('AUTO_COLOR', 'Automático (color)'), ('MANUAL', 'Manual'), ('UNMATCHED', 'Sin asignar')], default='UNMATCHED', max_length=20, verbose_name='método de asignación')),
                ('is_meeting', models.BooleanField(default=False, help_text='True si el evento tiene otros asistentes.', verbose_name='es reunión')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to='projects.project', verbose_name='proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'evento de calendario',
                'verbose_name_plural': 'eventos de calendario',
                'ordering': ['-start_time'],
                'unique_together': {('user', 'google_event_id')},
            },
        ),
        migrations.CreateModel(
            name='ProjectColorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color_id', models.CharField(max_length=20, verbose_name='ID de color en Google Calendar')),
                ('color_name', models.CharField(blank=True, max_length=50, verbose_name='nombre del color')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to='projects.project', verbose_name='proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_mappings', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'mapeo de color a proyecto',
                'verbose_name_plural': 'mapeos de color a proyecto',
                'unique_together': {('user', 'color_id')},
            },
        ),
    ]
