# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='imports/%Y/%m/', verbose_name='archivo')),
                ('source_type', models.CharField(choices=[('COR_SHEET', 'C.O.R. Data Proyectos'), ('FINANCIAL', 'Control Financiero'), ('HOLIDAYS', 'Festivos')], max_length=30, verbose_name='tipo de fuente')),
                ('status', models.CharField(choices=[('UPLOADED', 'Subido'), ('PREVIEWED', 'Previsualizado'), ('CONFIRMED', 'Confirmado'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='UPLOADED', max_length=20, verbose_name='estado')),
                ('records_total', models.IntegerField(default=0, verbose_name='registros totales')),
                ('records_imported', models.IntegerField(default=0, verbose_name='registros importados')),
                ('records_failed', models.IntegerField(default=0, verbose_name='registros fallidos')),
                ('errors', models.JSONField(blank=True, default=list, verbose_name='errores')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completado en')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL, verbose_name='subido por')),
            ],
            options={
                'verbose_name': 'trabajo de importación',
                'verbose_name_plural': 'trabajos de importación',
                'ordering': ['-created_at'],
            },
        ),
    ]
