# Generated by Django 5.1.15 on 2026-03-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='source_type',
            field=models.CharField(choices=[('COR_SHEET', 'C.O.R. Data Proyectos'), ('FINANCIAL', 'Control Financiero'), ('HOLIDAYS', 'Festivos'), ('LOGGRO_ACCOUNTING', 'Auxiliar Contable Loggro')], max_length=30, verbose_name='tipo de fuente'),
        ),
    ]
