# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('MADE', 'MADE'), ('SELECT', 'SELECT')], max_length=10, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_units', to=settings.AUTH_USER_MODEL, verbose_name='líder')),
            ],
            options={
                'verbose_name': 'unidad de negocio',
                'verbose_name_plural': 'unidades de negocio',
            },
        ),
        migrations.CreateModel(
            name='OrganizationalSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(choices=[('NEO', 'NEO'), ('IDI', 'IDI'), ('RED', 'RED'), ('CASH', 'CASH'), ('CORE', 'CORE'), ('BONES', 'BONES')], max_length=10, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('analogy', models.CharField(blank=True, help_text='Nombre metafórico del sistema.', max_length=200, verbose_name='analogía')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_systems', to=settings.AUTH_USER_MODEL, verbose_name='líder')),
            ],
            options={
                'verbose_name': 'sistema organizacional',
                'verbose_name_plural': 'sistemas organizacionales',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OperativeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='código')),
                ('name', models.CharField(help_text="Ej. 'Diseño y Visual', 'Visualización', 'Tech Ventas', 'Intel Financiera'.", max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('business_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operative_lines', to='organizations.businessunit', verbose_name='unidad de negocio')),
            ],
            options={
                'verbose_name': 'línea operativa',
                'verbose_name_plural': 'líneas operativas',
            },
        ),
    ]
