# Generated by Django 4.2.21 on 2026-02-28 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('CRITICAL', 'Crítico')], default='INFO', max_length=20, verbose_name='severidad')),
                ('category', models.CharField(choices=[('SCHEDULE_DEVIATION', 'Desviación de cronograma'), ('COST_OVERRUN', 'Sobrecosto'), ('CAPACITY_OVERLOAD', 'Sobrecarga de capacidad'), ('PAYMENT_OVERDUE', 'Pago vencido'), ('MILESTONE_DUE', 'Hito próximo'), ('SATISFACTION_LOW', 'Satisfacción baja')], max_length=50, verbose_name='categoría')),
                ('title', models.CharField(max_length=300, verbose_name='título')),
                ('message', models.TextField(verbose_name='mensaje')),
                ('is_read', models.BooleanField(default=False, verbose_name='leída')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='resuelta')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de resolución')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='projects.project', verbose_name='proyecto')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='resuelta por')),
                ('target_users', models.ManyToManyField(blank=True, related_name='alerts', to=settings.AUTH_USER_MODEL, verbose_name='usuarios destinatarios')),
            ],
            options={
                'verbose_name': 'alerta',
                'verbose_name_plural': 'alertas',
                'ordering': ['-created_at'],
            },
        ),
    ]
